
path_w="C:/Users/amaru/OneDrive/Escritorio/CODES/00017_JAC_monosteira/Modelos_Maxent/Maxent_introduced/Modelos"
setwd(path_w)
print("corriendo 1/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/H1"),
                        args=c('betamultiplier=1',
                               'linear=false',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 2/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                         path=glue("{path_w}/H2"),
                         args=c('betamultiplier=2',
                                'linear=false',
                                'quadratic=false',
                                'product=false',
                                'threshold=false',
                                'hinge=true',
                                "outputformat=logistic",
                                "autofeature=false"))
print("corriendo 3/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                         path=glue("{path_w}/H3"),
                         args=c('betamultiplier=3',
                                'linear=false',
                                'quadratic=false',
                                'product=false',
                                'threshold=false',
                                'hinge=true',
                                "outputformat=logistic",
                                "autofeature=false"))
print("corriendo 4/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                         path=glue("{path_w}/H4"),
                         args=c('betamultiplier=4',
                                'linear=false',
                                'quadratic=false',
                                'product=false',
                                'threshold=false',
                                'hinge=true',
                                "outputformat=logistic",
                                "autofeature=false"))
print("corriendo 5/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/H05"),
                        args=c('betamultiplier=0.5',
                               'linear=false',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 6/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/H15"),
                        args=c('betamultiplier=1.5',
                               'linear=false',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 7/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/H25"),
                        args=c('betamultiplier=2.5',
                               'linear=false',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 8/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/H35"),
                        args=c('betamultiplier=3.5',
                               'linear=false',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 9/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L1"),
                        args=c('betamultiplier=1',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 10/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L2"),
                        args=c('betamultiplier=2',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 11/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L3"),
                        args=c('betamultiplier=3',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 12/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L4"),
                        args=c('betamultiplier=4',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 13/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L05"),
                        args=c('betamultiplier=0.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 14/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L15"),
                        args=c('betamultiplier=1.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 15/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L25"),
                        args=c('betamultiplier=2.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 16/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/L35"),
                        args=c('betamultiplier=3.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 17/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH1"),
                        args=c('betamultiplier=1',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 18/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH2"),
                        args=c('betamultiplier=2',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 19/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH3"),
                        args=c('betamultiplier=3',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 20/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH4"),
                        args=c('betamultiplier=4',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 21/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH05"),
                        args=c('betamultiplier=0.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 22/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH15"),
                        args=c('betamultiplier=1.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 23/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH25"),
                        args=c('betamultiplier=2.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 24/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LH35"),
                        args=c('betamultiplier=3.5',
                               'linear=true',
                               'quadratic=false',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 25/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ1"),
                        args=c('betamultiplier=1',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 26/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ2"),
                        args=c('betamultiplier=2',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 27/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ3"),
                        args=c('betamultiplier=3',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 28/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ4"),
                        args=c('betamultiplier=4',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 29/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ05"),
                        args=c('betamultiplier=0.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 30/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ15"),
                        args=c('betamultiplier=1.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 31/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ25"),
                        args=c('betamultiplier=2.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 32/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LHQ335"),
                        args=c('betamultiplier=3.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 33/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ1"),
                        args=c('betamultiplier=1',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 34/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ2"),
                        args=c('betamultiplier=2',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 35/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ3"),
                        args=c('betamultiplier=3',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 36/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ4"),
                        args=c('betamultiplier=4',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 37/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ05"),
                        args=c('betamultiplier=0.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false",
                               "jackknife=true",
                               "responsecurves=true"))
print("corriendo 38/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ15"),
                        args=c('betamultiplier=1.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 39/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ25"),
                        args=c('betamultiplier=2.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 40/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/LQ35"),
                        args=c('betamultiplier=3.5',
                               'linear=true',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 41/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q1"),
                        args=c('betamultiplier=1',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 42/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q2"),
                        args=c('betamultiplier=2',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 43/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q3"),
                        args=c('betamultiplier=3',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 44/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q4"),
                        args=c('betamultiplier=4',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 45/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q05"),
                        args=c('betamultiplier=0.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 46/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q15"),
                        args=c('betamultiplier=1.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 47/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q25"),
                        args=c('betamultiplier=2.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 48/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/Q35"),
                        args=c('betamultiplier=3.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=false',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 49/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH1"),
                        args=c('betamultiplier=1',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 50/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH2"),
                        args=c('betamultiplier=2',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 51/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH3"),
                        args=c('betamultiplier=3',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 52/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH4"),
                        args=c('betamultiplier=4',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 53/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH05"),
                        args=c('betamultiplier=0.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 54/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH15"),
                        args=c('betamultiplier=1.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 55/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH25"),
                        args=c('betamultiplier=2.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))
print("corriendo 56/56")
modelo<-enmtools.maxent(monosteira, pca1$rasters,
                        path=glue("{path_w}/QH35"),
                        args=c('betamultiplier=3.5',
                               'linear=false',
                               'quadratic=true',
                               'product=false',
                               'threshold=false',
                               'hinge=true',
                               "outputformat=logistic",
                               "autofeature=false"))

